### ISSUE TITLE
[Errno 13] Permission denied error on Fedora 36

### ISSUE THREAD

**Issue by clhuby** [freedomofpress/dangerzone#260] opened 2022-11-24 03:56 UTC
Fedora 36 with all updates applied. Selecting a document and then pressing Convert shows an error "[Errno 13] Permission denied: '/tmp/input_file'"  I have tried opening the file from a different location and renaming the file but the issue remains.

Running from terminal shows the following log:

`[fhit@fedora /]$ dangerzone
QSocketNotifier: Can only be used with threads started with QThread
QObject::connect: No such signal QPlatformNativeInterface::systemTrayWindowChanged(QScreen*)
[INFO] > /usr/bin/podman run --network none -u dangerzone --security-opt no-new-privileges --userns keep-id --cap-drop all --rm -v /home/fhit/Downloads/VFST.pdf:/tmp/input_file -v /home/fhit/.config/dangerzone/tmp/tmptdfvm10l/pixels:/dangerzone dangerzone.rocks/dangerzone /usr/bin/python3 /usr/local/bin/dangerzone.py document-to-pixels
[ERROR] Invalid JSON returned from container: Traceback (most recent call last):

[ERROR] Invalid JSON returned from container:   File "/usr/local/bin/dangerzone.py", line 542, in <module>

[ERROR] Invalid JSON returned from container:     sys.exit(main())

[ERROR] Invalid JSON returned from container:   File "/usr/local/bin/dangerzone.py", line 533, in main

[ERROR] Invalid JSON returned from container:     return converter.document_to_pixels()

[ERROR] Invalid JSON returned from container:   File "/usr/local/bin/dangerzone.py", line 105, in document_to_pixels

[ERROR] Invalid JSON returned from container:     mime_type = mime.from_file("/tmp/input_file")

[ERROR] Invalid JSON returned from container:   File "/usr/lib/python3.10/site-packages/magic/__init__.py", line 111, in from_file

[ERROR] Invalid JSON returned from container:     with _real_open(filename):

[ERROR] Invalid JSON returned from container: PermissionError: [Errno 13] Permission denied: '/tmp/input_file'

[ERROR] documents-to-pixels failed`

**Comment by apyrgio** [comment] 2022-11-24 09:34
This looks like a duplicate of https://github.com/freedomofpress/dangerzone/issues/157. This may happen when the file has weird permissions, especially when its not readable by Unix "others". Can you share here the output of:

```
ls -l /home/fhit/Downloads/VFST.pdf
```

to verify that it's indeed the same case?

**Closed** 2023-02-16 23:19 UTC
