### ISSUE TITLE
Qubes: Unique file paths for each document

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#454] opened 2023-06-21 08:22 UTC
The Qubes isolation provider currently uses deterministic file paths when converting each document. This will pose an issue if at some point we happen to have multiple Dangerzone instances running, or support parallel conversions.

Use unique file paths for each document, so that we can avoid name clashes in the future.

**Comment by deeplow** [comment] 2023-06-21 08:24
Is this similar or a duplicate of https://github.com/freedomofpress/dangerzone/issues/436?

**Comment by apyrgio** [comment] 2023-06-21 08:37
Damn, it's a duplicate. Nice catch, I didn't remember we had it because it was not linked to our #413  issue.

**Closed** 2023-06-21 08:37 UTC
Labels: bug, P:Qubes
