### ISSUE TITLE
Windows 10: Dangerzone 0.3.1 will not install

### ISSUE THREAD

**Issue by feathered-arch** [freedomofpress/dangerzone#150] opened 2022-03-10 20:20 UTC
Installer states that a newer version is installed, and that in order to downgrade the newer version must first be uninstalled. 

I have never had Dangerzone installed on any of my devices (and I only learned about this software today).

**Comment by clock-cycle-horse** [comment] 2022-03-21 21:29
RE: "Installer states that a newer version is installed, and that in order to downgrade the newer version must first be uninstalled.
I have never had Dangerzone installed on any of my devices"

I have exact same issue. The latest version and earlier version generate the same message quoted above. I too have never installed DangerZone

**Comment by Le1b1** [comment] 2022-05-20 06:36
Maybe related to #153 ?

**Comment by deeplow** [comment] 2022-07-27 11:28
@feathered-arch and @clock-cycle-horse can you confirm that you had onionshare installed before?

**Comment by feathered-arch** [comment] 2022-07-27 15:22
> @feathered-arch and @clock-cycle-horse can you confirm that you had onionshare installed before?

Confirmed.

**Comment by deeplow** [comment] 2022-07-29 11:07
Thanks @feathered-arch. Closing this as it is a duplicate of #153.

**Closed by deeplow** 2022-07-29 11:07 UTC
Labels: bug, windows
