### ISSUE TITLE
Silicon Mac - Error during installation of the dangerzone image for `0.8.0`

### ISSUE THREAD

**Issue by charginglabrador** [freedomofpress/dangerzone#993] opened 2024-11-07 02:48 UTC
### What happened?

Just updated Dangerzone to 0.8.0 and am getting this message when launching the app:
<img width="603" alt="Screenshot 2024-11-06 at 9 45 55 PM" src="https://github.com/user-attachments/assets/99fdb360-41f5-42ce-99f8-81da81a3d2d6">

Error content:
`Traceback (most recent call last):
    File "dangerzone/gui/main_window.py", line 411, in run
    File "dangerzone/isolation_provider/container.py", line 194, in install
    File "dangerzone/isolation_provider/container.py", line 245, in is_container_installed
dangerzone.isolation_provider.container.ImageNotPresentException: Image is not listed after installation. Bailing out.`

### operating system version

macOS Sequoia 15.0.1

### Processor type

Apple Silicon

### Dangerzone version

0.8.0

**Comment by almet** [comment] 2024-11-07 07:56
Hey, thanks for reporting the error. Can you please fill in the missing bits about docker info maybe?

```bash
docker version
docker info -f 'json'
docker images
docker run hello-world
```

I'll try to reproduce locally today and report back. (Then, we will issue a bugfix release as soon as a fix is out)

**Comment by almet** [comment] 2024-11-07 09:07
I've downloaded [the latest arm64 `.dmg` for 0.8.0](https://github.com/freedomofpress/dangerzone/releases/download/v0.8.0/Dangerzone-0.8.0-arm64.dmg) and (un)fortunately cannot reproduce the error you see on my M1 Silicon system (Sonoma 14.5).

I'm really curious about the output of the aforementioned commands, as they will give us some more details on the versions you run. Especially, I'm wondering what's the version of Docker Desktop you're running.

Here are the output of these commands on my personal m1 machine, for later reference:

<details><summary>Details</summary>
<p>

```bash
> docker version
Client: Docker Engine - Community
 Version:           26.1.3
 API version:       1.45
 Go version:        go1.22.3
 Git commit:        b72abbb6f0
 Built:             Thu May 16 07:47:24 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.35.1 (173168)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```bash
> docker info -f 'json'
{
  "ID": "b7261d95-d4b7-4a8d-ae8d-c830155731c6",
  "Containers": 4,
  "ContainersRunning": 0,
  "ContainersPaused": 0,
  "ContainersStopped": 4,
  "Images": 4,
  "Driver": "overlay2",
  "DriverStatus": [
    [
      "Backing Filesystem",
      "extfs"
    ],
    [
      "Supports d_type",
      "true"
    ],
    [
      "Using metacopy",
      "false"
    ],
    [
      "Native Overlay Diff",
      "true"
    ],
    [
      "userxattr",
      "false"
    ]
  ],
  "Plugins": {
    "Volume": [
      "local"
    ],
    "Network": [
      "bridge",
      "host",
      "ipvlan",
      "macvlan",
      "null",
      "overlay"
    ],
    "Authorization": null,
    "Log": [
      "awslogs",
      "fluentd",
      "gcplogs",
      "gelf",
      "journald",
      "json-file",
      "local",
      "splunk",
      "syslog"
    ]
  },
  "MemoryLimit": true,
  "SwapLimit": true,
  "CpuCfsPeriod": true,
  "CpuCfsQuota": true,
  "CPUShares": true,
  "CPUSet": true,
  "PidsLimit": true,
  "IPv4Forwarding": true,
  "BridgeNfIptables": true,
  "BridgeNfIp6tables": true,
  "Debug": false,
  "NFd": 50,
  "OomKillDisable": false,
  "NGoroutines": 67,
  "SystemTime": "2024-11-07T08:58:45.284542962Z",
  "LoggingDriver": "json-file",
  "CgroupDriver": "cgroupfs",
  "CgroupVersion": "2",
  "NEventsListener": 12,
  "KernelVersion": "6.10.11-linuxkit",
  "OperatingSystem": "Docker Desktop",
  "OSVersion": "",
  "OSType": "linux",
  "Architecture": "aarch64",
  "IndexServerAddress": "https://index.docker.io/v1/",
  "RegistryConfig": {
    "AllowNondistributableArtifactsCIDRs": null,
    "AllowNondistributableArtifactsHostnames": null,
    "InsecureRegistryCIDRs": [
      "127.0.0.0/8"
    ],
    "IndexConfigs": {
      "docker.io": {
        "Name": "docker.io",
        "Mirrors": [],
        "Secure": true,
        "Official": true
      },
      "hubproxy.docker.internal:5555": {
        "Name": "hubproxy.docker.internal:5555",
        "Mirrors": [],
        "Secure": false,
        "Official": false
      }
    },
    "Mirrors": null
  },
  "NCPU": 8,
  "MemTotal": 8218251264,
  "GenericResources": null,
  "DockerRootDir": "/var/lib/docker",
  "HttpProxy": "http.docker.internal:3128",
  "HttpsProxy": "http.docker.internal:3128",
  "NoProxy": "hubproxy.docker.internal",
  "Name": "docker-desktop",
  "Labels": [
    "com.docker.desktop.address=unix:///Users/alexis/Library/Containers/com.docker.docker/Data/docker-cli.sock"
  ],
  "ExperimentalBuild": false,
  "ServerVersion": "27.3.1",
  "Runtimes": {
    "io.containerd.runc.v2": {
      "path": "runc",
      "status": {
        "org.opencontainers.runtime-spec.features": "{\"ociVersionMin\":\"1.0.0\",\"ociVersionMax\":\"1.0.2-dev\",\"hooks\":[\"prestart\",\"createRuntime\",\"createContainer\",\"startContainer\",\"poststart\",\"poststop\"],\"mountOptions\":[\"acl\",\"async\",\"atime\",\"bind\",\"defaults\",\"dev\",\"diratime\",\"dirsync\",\"exec\",\"iversion\",\"lazytime\",\"loud\",\"mand\",\"noacl\",\"noatime\",\"nodev\",\"nodiratime\",\"noexec\",\"noiversion\",\"nolazytime\",\"nomand\",\"norelatime\",\"nostrictatime\",\"nosuid\",\"nosymfollow\",\"private\",\"ratime\",\"rbind\",\"rdev\",\"rdiratime\",\"relatime\",\"remount\",\"rexec\",\"rnoatime\",\"rnodev\",\"rnodiratime\",\"rnoexec\",\"rnorelatime\",\"rnostrictatime\",\"rnosuid\",\"rnosymfollow\",\"ro\",\"rprivate\",\"rrelatime\",\"rro\",\"rrw\",\"rshared\",\"rslave\",\"rstrictatime\",\"rsuid\",\"rsymfollow\",\"runbindable\",\"rw\",\"shared\",\"silent\",\"slave\",\"strictatime\",\"suid\",\"symfollow\",\"sync\",\"tmpcopyup\",\"unbindable\"],\"linux\":{\"namespaces\":[\"cgroup\",\"ipc\",\"mount\",\"network\",\"pid\",\"user\",\"uts\"],\"capabilities\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_DAC_READ_SEARCH\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_SETGID\",\"CAP_SETUID\",\"CAP_SETPCAP\",\"CAP_LINUX_IMMUTABLE\",\"CAP_NET_BIND_SERVICE\",\"CAP_NET_BROADCAST\",\"CAP_NET_ADMIN\",\"CAP_NET_RAW\",\"CAP_IPC_LOCK\",\"CAP_IPC_OWNER\",\"CAP_SYS_MODULE\",\"CAP_SYS_RAWIO\",\"CAP_SYS_CHROOT\",\"CAP_SYS_PTRACE\",\"CAP_SYS_PACCT\",\"CAP_SYS_ADMIN\",\"CAP_SYS_BOOT\",\"CAP_SYS_NICE\",\"CAP_SYS_RESOURCE\",\"CAP_SYS_TIME\",\"CAP_SYS_TTY_CONFIG\",\"CAP_MKNOD\",\"CAP_LEASE\",\"CAP_AUDIT_WRITE\",\"CAP_AUDIT_CONTROL\",\"CAP_SETFCAP\",\"CAP_MAC_OVERRIDE\",\"CAP_MAC_ADMIN\",\"CAP_SYSLOG\",\"CAP_WAKE_ALARM\",\"CAP_BLOCK_SUSPEND\",\"CAP_AUDIT_READ\",\"CAP_PERFMON\",\"CAP_BPF\",\"CAP_CHECKPOINT_RESTORE\"],\"cgroup\":{\"v1\":true,\"v2\":true,\"systemd\":true,\"systemdUser\":true},\"seccomp\":{\"enabled\":true,\"actions\":[\"SCMP_ACT_ALLOW\",\"SCMP_ACT_ERRNO\",\"SCMP_ACT_KILL\",\"SCMP_ACT_KILL_PROCESS\",\"SCMP_ACT_KILL_THREAD\",\"SCMP_ACT_LOG\",\"SCMP_ACT_NOTIFY\",\"SCMP_ACT_TRACE\",\"SCMP_ACT_TRAP\"],\"operators\":[\"SCMP_CMP_EQ\",\"SCMP_CMP_GE\",\"SCMP_CMP_GT\",\"SCMP_CMP_LE\",\"SCMP_CMP_LT\",\"SCMP_CMP_MASKED_EQ\",\"SCMP_CMP_NE\"],\"archs\":[\"SCMP_ARCH_AARCH64\",\"SCMP_ARCH_ARM\",\"SCMP_ARCH_MIPS\",\"SCMP_ARCH_MIPS64\",\"SCMP_ARCH_MIPS64N32\",\"SCMP_ARCH_MIPSEL\",\"SCMP_ARCH_MIPSEL64\",\"SCMP_ARCH_MIPSEL64N32\",\"SCMP_ARCH_PPC\",\"SCMP_ARCH_PPC64\",\"SCMP_ARCH_PPC64LE\",\"SCMP_ARCH_RISCV64\",\"SCMP_ARCH_S390\",\"SCMP_ARCH_S390X\",\"SCMP_ARCH_X32\",\"SCMP_ARCH_X86\",\"SCMP_ARCH_X86_64\"]},\"apparmor\":{\"enabled\":true},\"selinux\":{\"enabled\":true}},\"annotations\":{\"io.github.seccomp.libseccomp.version\":\"2.5.4\",\"org.opencontainers.runc.checkpoint.enabled\":\"true\",\"org.opencontainers.runc.commit\":\"v1.1.13-0-g58aa920\",\"org.opencontainers.runc.version\":\"1.1.13\"}}"
      }
    },
    "runc": {
      "path": "runc",
      "status": {
        "org.opencontainers.runtime-spec.features": "{\"ociVersionMin\":\"1.0.0\",\"ociVersionMax\":\"1.0.2-dev\",\"hooks\":[\"prestart\",\"createRuntime\",\"createContainer\",\"startContainer\",\"poststart\",\"poststop\"],\"mountOptions\":[\"acl\",\"async\",\"atime\",\"bind\",\"defaults\",\"dev\",\"diratime\",\"dirsync\",\"exec\",\"iversion\",\"lazytime\",\"loud\",\"mand\",\"noacl\",\"noatime\",\"nodev\",\"nodiratime\",\"noexec\",\"noiversion\",\"nolazytime\",\"nomand\",\"norelatime\",\"nostrictatime\",\"nosuid\",\"nosymfollow\",\"private\",\"ratime\",\"rbind\",\"rdev\",\"rdiratime\",\"relatime\",\"remount\",\"rexec\",\"rnoatime\",\"rnodev\",\"rnodiratime\",\"rnoexec\",\"rnorelatime\",\"rnostrictatime\",\"rnosuid\",\"rnosymfollow\",\"ro\",\"rprivate\",\"rrelatime\",\"rro\",\"rrw\",\"rshared\",\"rslave\",\"rstrictatime\",\"rsuid\",\"rsymfollow\",\"runbindable\",\"rw\",\"shared\",\"silent\",\"slave\",\"strictatime\",\"suid\",\"symfollow\",\"sync\",\"tmpcopyup\",\"unbindable\"],\"linux\":{\"namespaces\":[\"cgroup\",\"ipc\",\"mount\",\"network\",\"pid\",\"user\",\"uts\"],\"capabilities\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_DAC_READ_SEARCH\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_SETGID\",\"CAP_SETUID\",\"CAP_SETPCAP\",\"CAP_LINUX_IMMUTABLE\",\"CAP_NET_BIND_SERVICE\",\"CAP_NET_BROADCAST\",\"CAP_NET_ADMIN\",\"CAP_NET_RAW\",\"CAP_IPC_LOCK\",\"CAP_IPC_OWNER\",\"CAP_SYS_MODULE\",\"CAP_SYS_RAWIO\",\"CAP_SYS_CHROOT\",\"CAP_SYS_PTRACE\",\"CAP_SYS_PACCT\",\"CAP_SYS_ADMIN\",\"CAP_SYS_BOOT\",\"CAP_SYS_NICE\",\"CAP_SYS_RESOURCE\",\"CAP_SYS_TIME\",\"CAP_SYS_TTY_CONFIG\",\"CAP_MKNOD\",\"CAP_LEASE\",\"CAP_AUDIT_WRITE\",\"CAP_AUDIT_CONTROL\",\"CAP_SETFCAP\",\"CAP_MAC_OVERRIDE\",\"CAP_MAC_ADMIN\",\"CAP_SYSLOG\",\"CAP_WAKE_ALARM\",\"CAP_BLOCK_SUSPEND\",\"CAP_AUDIT_READ\",\"CAP_PERFMON\",\"CAP_BPF\",\"CAP_CHECKPOINT_RESTORE\"],\"cgroup\":{\"v1\":true,\"v2\":true,\"systemd\":true,\"systemdUser\":true},\"seccomp\":{\"enabled\":true,\"actions\":[\"SCMP_ACT_ALLOW\",\"SCMP_ACT_ERRNO\",\"SCMP_ACT_KILL\",\"SCMP_ACT_KILL_PROCESS\",\"SCMP_ACT_KILL_THREAD\",\"SCMP_ACT_LOG\",\"SCMP_ACT_NOTIFY\",\"SCMP_ACT_TRACE\",\"SCMP_ACT_TRAP\"],\"operators\":[\"SCMP_CMP_EQ\",\"SCMP_CMP_GE\",\"SCMP_CMP_GT\",\"SCMP_CMP_LE\",\"SCMP_CMP_LT\",\"SCMP_CMP_MASKED_EQ\",\"SCMP_CMP_NE\"],\"archs\":[\"SCMP_ARCH_AARCH64\",\"SCMP_ARCH_ARM\",\"SCMP_ARCH_MIPS\",\"SCMP_ARCH_MIPS64\",\"SCMP_ARCH_MIPS64N32\",\"SCMP_ARCH_MIPSEL\",\"SCMP_ARCH_MIPSEL64\",\"SCMP_ARCH_MIPSEL64N32\",\"SCMP_ARCH_PPC\",\"SCMP_ARCH_PPC64\",\"SCMP_ARCH_PPC64LE\",\"SCMP_ARCH_RISCV64\",\"SCMP_ARCH_S390\",\"SCMP_ARCH_S390X\",\"SCMP_ARCH_X32\",\"SCMP_ARCH_X86\",\"SCMP_ARCH_X86_64\"]},\"apparmor\":{\"enabled\":true},\"selinux\":{\"enabled\":true}},\"annotations\":{\"io.github.seccomp.libseccomp.version\":\"2.5.4\",\"org.opencontainers.runc.checkpoint.enabled\":\"true\",\"org.opencontainers.runc.commit\":\"v1.1.13-0-g58aa920\",\"org.opencontainers.runc.version\":\"1.1.13\"}}"
      }
    }
  },
  "DefaultRuntime": "runc",
  "Swarm": {
    "NodeID": "",
    "NodeAddr": "",
    "LocalNodeState": "inactive",
    "ControlAvailable": false,
    "Error": "",
    "RemoteManagers": null
  },
  "LiveRestoreEnabled": false,
  "Isolation": "",
  "InitBinary": "docker-init",
  "ContainerdCommit": {
    "ID": "472731909fa34bd7bc9c087e4c27943f9835f111",
    "Expected": "472731909fa34bd7bc9c087e4c27943f9835f111"
  },
  "RuncCommit": {
    "ID": "v1.1.13-0-g58aa920",
    "Expected": "v1.1.13-0-g58aa920"
  },
  "InitCommit": {
    "ID": "de40ad0",
    "Expected": "de40ad0"
  },
  "SecurityOptions": [
    "name=seccomp,profile=unconfined",
    "name=cgroupns"
  ],
  "CDISpecDirs": [],
  "Warnings": [
    "WARNING: daemon is not using the default seccomp profile"
  ],
  "ClientInfo": {
    "Debug": false,
    "Platform": {
      "Name": "Docker Engine - Community"
    },
    "Version": "26.1.3",
    "GitCommit": "b72abbb6f0",
    "GoVersion": "go1.22.3",
    "Os": "darwin",
    "Arch": "arm64",
    "BuildTime": "Thu May 16 07:47:24 2024",
    "Context": "desktop-linux",
    "Plugins": [
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v0.17.1-desktop.1",
        "ShortDescription": "Docker Buildx",
        "Name": "buildx",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-buildx"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v2.29.7-desktop.1",
        "ShortDescription": "Docker Compose",
        "Name": "compose",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-compose"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "0.0.37",
        "ShortDescription": "Get a shell into any image or container",
        "Name": "debug",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-debug"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v0.0.15",
        "ShortDescription": "Docker Desktop commands (Alpha)",
        "Name": "desktop",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-desktop"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v0.1.2",
        "ShortDescription": "Docker Dev Environments",
        "Name": "dev",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-dev"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v0.2.27",
        "ShortDescription": "Manages Docker extensions",
        "Name": "extension",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-extension"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v1.0.5",
        "ShortDescription": "Provide feedback, right in your terminal!",
        "Name": "feedback",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-feedback"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v1.3.0",
        "ShortDescription": "Creates Docker-related starter files for your project",
        "Name": "init",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-init"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Anchore Inc.",
        "Version": "0.6.0",
        "ShortDescription": "View the packaged-based Software Bill Of Materials (SBOM) for an image",
        "URL": "https://github.com/docker/sbom-cli-plugin",
        "Name": "sbom",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-sbom"
      },
      {
        "SchemaVersion": "0.1.0",
        "Vendor": "Docker Inc.",
        "Version": "v1.14.0",
        "ShortDescription": "Docker Scout",
        "Name": "scout",
        "Path": "/Users/alexis/.docker/cli-plugins/docker-scout"
      }
    ],
    "Warnings": null
  }
}
```
```bash
> docker images
REPOSITORY                        TAG       IMAGE ID       CREATED         SIZE
dangerzone.rocks/dangerzone       latest    c6eb6272f84d   6 days ago      1.07GB
directus/directus                 latest    8e7d936f4216   5 months ago    508MB
ghcr.io/orbstack/dmigrate-agent   1         ef92304d816a   15 months ago   5.98MB
httptoolkit/docker-socks-tunnel   v1.2.0    60dc49ba8589   17 months ago   1.81MB
```
</p>
</details>

**Comment by charginglabrador** [comment] 2024-11-07 13:17
Hi, here's the output from the commands

`docker version`
```
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.35.1 (173168)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

`docker info -f 'json'`
```
{"ID":"b999b74e-5795-4fb3-b209-5a52021b2371","Containers":0,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":0,"Images":0,"Driver":"vfs","DriverStatus":null,"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":55,"OomKillDisable":false,"NGoroutines":81,"SystemTime":"2024-11-07T13:11:32.725187667Z","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"2","NEventsListener":16,"KernelVersion":"6.10.11-linuxkit","OperatingSystem":"Docker Desktop","OSVersion":"","OSType":"linux","Architecture":"aarch64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":null,"AllowNondistributableArtifactsHostnames":null,"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true},"hubproxy.docker.internal:5555":{"Name":"hubproxy.docker.internal:5555","Mirrors":[],"Secure":false,"Official":false}},"Mirrors":null},"NCPU":11,"MemTotal":8217825280,"GenericResources":null,"DockerRootDir":"/mnt/firefly","HttpProxy":"http.docker.internal:3128","HttpsProxy":"http.docker.internal:3128","NoProxy":"hubproxy.docker.internal","Name":"docker-desktop","Labels":["com.docker.desktop.address=unix:///Users/labrador/Library/Containers/com.docker.docker/Data/docker-cli.sock"],"ExperimentalBuild":false,"ServerVersion":"27.3.1","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"472731909fa34bd7bc9c087e4c27943f9835f111","Expected":"472731909fa34bd7bc9c087e4c27943f9835f111"},"RuncCommit":{"ID":"v1.1.13-0-g58aa920","Expected":"v1.1.13-0-g58aa920"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=unconfined","name=cgroupns"],"CDISpecDirs":[],"Warnings":["WARNING: daemon is not using the default seccomp profile"],"ClientInfo":{"Debug":false,"Version":"27.3.1","GitCommit":"ce12230","GoVersion":"go1.22.7","Os":"darwin","Arch":"arm64","BuildTime":"Fri Sep 20 11:38:18 2024","Context":"desktop-linux","Plugins":[{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.17.1-desktop.1","ShortDescription":"Docker Buildx","Name":"buildx","Path":"/Users/labrador/.docker/cli-plugins/docker-buildx","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-buildx"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v2.29.7-desktop.1","ShortDescription":"Docker Compose","Name":"compose","Path":"/Users/labrador/.docker/cli-plugins/docker-compose","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-compose"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"0.0.37","ShortDescription":"Get a shell into any image or container","Name":"debug","Path":"/Users/labrador/.docker/cli-plugins/docker-debug","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-debug"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.0.15","ShortDescription":"Docker Desktop commands (Alpha)","Name":"desktop","Path":"/Users/labrador/.docker/cli-plugins/docker-desktop","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-desktop"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.1.2","ShortDescription":"Docker Dev Environments","Name":"dev","Path":"/Users/labrador/.docker/cli-plugins/docker-dev","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-dev"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.2.27","ShortDescription":"Manages Docker extensions","Name":"extension","Path":"/Users/labrador/.docker/cli-plugins/docker-extension","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-extension"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v1.0.5","ShortDescription":"Provide feedback, right in your terminal!","Name":"feedback","Path":"/Users/labrador/.docker/cli-plugins/docker-feedback","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-feedback"]},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v1.3.0","ShortDescription":"Creates Docker-related starter files for your project","Name":"init","Path":"/Users/labrador/.docker/cli-plugins/docker-init","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-init"]},{"SchemaVersion":"0.1.0","Vendor":"Anchore Inc.","Version":"0.6.0","ShortDescription":"View the packaged-based Software Bill Of Materials (SBOM) for an image","URL":"https://github.com/docker/sbom-cli-plugin","Name":"sbom","Path":"/Users/labrador/.docker/cli-plugins/docker-sbom","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-sbom"]},{"Name":"scan","Path":"/Users/labrador/.docker/cli-plugins/docker-scan","Err":"failed to fetch metadata: fork/exec /Users/labrador/.docker/cli-plugins/docker-scan: no such file or directory"},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v1.14.0","ShortDescription":"Docker Scout","Name":"scout","Path":"/Users/labrador/.docker/cli-plugins/docker-scout","ShadowedPaths":["/usr/local/lib/docker/cli-plugins/docker-scout"]}],"Warnings":null}}
```
`docker images`
```
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
```

`docker run hello-world`
```
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
478afc919002: Pull complete
Digest: sha256:d211f485f2dd1dee407a80973c8f129f00d54604d2c90732e8e320e5038a0348
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (arm64v8)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/
```

**Comment by almet** [comment] 2024-11-07 13:50
Thanks for providing this additional data :handshake: 

It seems you are using the `vfs` storage driver where I'm using the `overlay2` one.

From [Docker docs](https://docs.docker.com/engine/storage/drivers/select-storage-driver/)

> The vfs storage driver is intended for testing purposes, and for situations where no copy-on-write filesystem can be used. Performance of this storage driver is poor, and is not generally recommended for production use.
> The vfs storage driver is usually not the best choice, and primarily intended for debugging purposes in situations where no other storage-driver is supported.

Are you in such a setting? Out of curiosity, did you made a change about the storage driver yourself? How did you install Docker Desktop?

Can you try switching to `overlay2`? I'm not sure how to proceed to do this, but maybe reinstalling Docker Desktop might help you here since it's the default setting.

PS: First I was afraid (I was petrified ;)) that a raw installation of Docker Desktop + Dangerzone 0.8.0 on a Silicon Chip wouldn't work, but it seem to be working fine after an installation on a friends machine with just all the setting set to default.

**Comment by charginglabrador** [comment] 2024-11-07 15:17
I just reinstalled Docker and things seem to be working! Was able to launch dangerzone and successfully make a PDF safe.

Thanks so much for the support and working on this really important software!

Just a question: do you know of similar tools for other filetypes? (ex. image formats like JPEG)

**Comment by apyrgio** [comment] 2024-11-07 15:59
Ok, great to know that reinstalling Docker Desktop fixed it, but it's kind of a bummer that it mysteriously left users in that state. We'll see if Podman Desktop can somehow fit the bill.

As for similar software, that's a good question. We should have a list at some point, but truth is that this space is a bit niche - there are not that many tools out there. If you're looking for metadata redaction, [Metadata Cleaner](https://gitlab.com/rmnvgr/metadata-cleaner) operated in the same space as us. Unfortunately, it's not maintained anymore. If you're looking for sanitization, I haven't tested anything else than Qubes' TrustedPDF to be honest.

Just in case you're not aware though, Dangerzone can handle JPEG files ,not just PDFs. Actually, we have a [long list of filetypes we support](https://github.com/freedomofpress/dangerzone?tab=readme-ov-file#some-features):

> - PDF (`.pdf`)
> - Microsoft Word (`.docx`, `.doc`)
> - Microsoft Excel (`.xlsx`, `.xls`)
> - Microsoft PowerPoint (`.pptx`, `.ppt`)
> - ODF Text (`.odt`)
> - ODF Spreadsheet (`.ods`)
> - ODF Presentation (`.odp`)
> - ODF Graphics (`.odg`)
> - Hancom HWP (Hangul Word Processor) (`.hwp`, `.hwpx`)
>   * Not supported on
>     [Qubes OS](https://github.com/freedomofpress/dangerzone/issues/494)
> - EPUB (`.epub`)
> - Jpeg (`.jpg`, `.jpeg`)
> - GIF (`.gif`)
> - PNG (`.png`)
> - SVG (`.svg`)
> - other image formats (`.bmp`, `.pnm`, `.pbm`, `.ppm`)

Closing this issue now that the original problem is fixed.

**Closed by apyrgio** 2024-11-07 15:59 UTC
Labels: bug

**Comment by almet** [comment] 2024-11-07 16:31
hey @charginglabrador thanks for the feedback, and happy to see that the issue is resolved on your end. I'm still curious about why you had `vfs` enabled, so if you have any feedback on this, and on how / when you installed Docker Desktop, that would be helpful for us in order to understand how you ended up in this situation.

**Comment by charginglabrador** [comment] 2024-11-10 18:08
> Ok, great to know that reinstalling Docker Desktop fixed it, but it's kind of a bummer that it mysteriously left users in that state. We'll see if Podman Desktop can somehow fit the bill.
> 
> As for similar software, that's a good question. We should have a list at some point, but truth is that this space is a bit niche - there are not that many tools out there. If you're looking for metadata redaction, [Metadata Cleaner](https://gitlab.com/rmnvgr/metadata-cleaner) operated in the same space as us. Unfortunately, it's not maintained anymore. If you're looking for sanitization, I haven't tested anything else than Qubes' TrustedPDF to be honest.
> 
> Just in case you're not aware though, Dangerzone can handle JPEG files ,not just PDFs. Actually, we have a [long list of filetypes we support](https://github.com/freedomofpress/dangerzone?tab=readme-ov-file#some-features):
> 
> > * PDF (`.pdf`)
> > * Microsoft Word (`.docx`, `.doc`)
> > * Microsoft Excel (`.xlsx`, `.xls`)
> > * Microsoft PowerPoint (`.pptx`, `.ppt`)
> > * ODF Text (`.odt`)
> > * ODF Spreadsheet (`.ods`)
> > * ODF Presentation (`.odp`)
> > * ODF Graphics (`.odg`)
> > * Hancom HWP (Hangul Word Processor) (`.hwp`, `.hwpx`)
> >   
> >   * Not supported on
> >     [Qubes OS](https://github.com/freedomofpress/dangerzone/issues/494)
> > * EPUB (`.epub`)
> > * Jpeg (`.jpg`, `.jpeg`)
> > * GIF (`.gif`)
> > * PNG (`.png`)
> > * SVG (`.svg`)
> > * other image formats (`.bmp`, `.pnm`, `.pbm`, `.ppm`)
> 
> Closing this issue now that the original problem is fixed.

Oh great! Didn't realize it could handle so many.

**Comment by charginglabrador** [comment] 2024-11-10 18:10
> hey @charginglabrador thanks for the feedback, and happy to see that the issue is resolved on your end. I'm still curious about why you had `vfs` enabled, so if you have any feedback on this, and on how / when you installed Docker Desktop, that would be helpful for us in order to understand how you ended up in this situation.

I'm not sure, I just installed Docker Desktop for this app and haven't touched it for anything else. I'm not very tech savvy so I could have turned it on accidentally. I'm pretty sure I downloaded it off the Docker website.
