### ISSUE TITLE
Error converting document to PDF, LibreOffice timed out after 60 seconds

### ISSUE THREAD

**Issue by michaelpierre** [freedomofpress/dangerzone#149] opened 2022-03-08 23:48 UTC
![dangerzone-error](https://user-images.githubusercontent.com/61525415/157344652-c5245ca5-3258-48fc-a097-e60005dfda22.png)

I have a 2.1 MB .xlsx Excel file i'm trying to convert to a PDF using DangerZone. I keep getting the captioned error. Other .xlsx Excel files convert successfully using DangerZone except this file. DangerZone is installed in a Ubuntu 20.04.4 VMWare VM on a Windows 11 host. Any idea why this is happening?

**Comment by yveszoundi** [comment] 2022-04-10 16:35
@michaelpierre , Many of the conversion operations rely on "external programs" such as LibreOffice, executed with a defined timeout. The problem is  determining the expected time limit for a program to either complete or be considered as a zombie process: _should a timeout be even set/guessed by `dangerzone` in the first place_????

### Potential mitigation options
#### Do not set an execution timeout at all
- **Pros**: If a process does not complete "quickly", there could be several legit reasons (_large_ documents, lots of images, OCR enabled, etc.). Letting the program (LibreOffice, etc.) complete gracefully is often reasonable.
- **Cons**: If a process hangs in the container during the conversion (and [this has happened before](https://github.com/firstlookmedia/dangerzone/issues/70#issuecomment-615836957)), there's no user feedback.

#### Use a timeout that is proportional to the number of pages
- **Pros**: This will work in many situations for most people, unless documents have tons of graphics.
- **Cons**: There is more than just the number of pages to account for (number/size of images, available RAM and CPU, etc.).

### Similar issues previously reported
- https://github.com/firstlookmedia/dangerzone/issues/70
- https://github.com/firstlookmedia/dangerzone/issues/58
- https://github.com/firstlookmedia/dangerzone/issues/146

### Other references
I created [another dangerzone version written in Rust](https://github.com/rimerosolutions/dangerzone-rust) due to this problem and for personal exploration. It's more about explaining the rationale as it pertains to this issue, rather than advertising my own minimal solution (developer audience).

- I often run _dangerzone_ inside a dedicated VM (RAM limit of 1GB), 60 secs timeouts are not desired. 
- I avoid scripting languages such as Python, if possible: for many corporate laptops the RAM is often 8GB-16GB. Scripting languages tend to abuse resources: if your PC starts _swapping_ (many apps open), you could see more timeouts.

**Comment by yveszoundi** [comment] 2022-05-01 04:38
@michaelpierre , I created an [initial release of  dangerzone-rust](https://github.com/rimerosolutions/dangerzone-rust/releases/tag/0.0.1), in case it might be _temporarily useful_ to you or others: 

- Linux binaries are available (GUI and CLI programs), along with MacOS and Windows support
  - The `dangerzone-gui` is an [AppImage](https://appimage.org/) under Linux that might require the `fuse2` dependency to run
  - Other Linux binaries are standalone zero-dependency programs (statically linked)
- There's also a minimal "Online Service": Web usable by several users (home network and/or possibly intranet?)

**Comment by apyrgio** [comment] 2022-11-23 11:21
We will bump the timeout in the 0.4.0 release (not yet released). Let's keep this issue open for a little while, so that we can see if an increased timeout helps. Please comment here once you have 0.4.0 installed and this bug still affects you. Else, we can close this issue.

Note that increasing the timeout won't solve the underlying issue, but it will make it very rare, which is a good first step.

**Comment by apyrgio** [comment] 2023-06-13 14:44
Hi folks. I think this is the last issue for timeouts that is still open, so quick announcement for those who haven't seen the [v0.4.1 changelog](https://github.com/freedomofpress/dangerzone/blob/v0.4.1/CHANGELOG.md):

> Feature: Adjust conversion timeouts based on the document's pages/size, and allow users to disable them with `--disable-timeouts` (available when you run the Dangerzone from the terminal) (https://github.com/freedomofpress/dangerzone/issues/327)

If you still encounter timeout errors, then your environment may be low on resources, as Yves already suggested. In that case, feel free to use the `--disable-timeouts` option. Hopefully, this way Dangerzone will be able to detect hung processes within a reasonable time, and not fail even in machines that are swapping out.

If you still encounter a problem and none of the above solutions work, please reach out to us and create a new issue. For now, we consider this problem resolved.

**Closed by apyrgio** 2023-06-13 14:44 UTC
Labels: bug, timeout
