### ISSUE TITLE
Dangerzone error in Linux Mint

### ISSUE THREAD

**Issue by DeltaEpsilon19498** [freedomofpress/dangerzone#661] opened 2023-12-24 20:34 UTC
I am in Linux Mint. I am using the jammy repo. Dangerzone has been working perfectly for me, but today it will no longer work. If I try to run it, I get the following error.

Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.5.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/dangerzone/__init__.py", line 16, in <module>
    from .gui import gui_main as main
  File "/usr/lib/python3/dist-packages/dangerzone/gui/__init__.py", line 30, in <module>
    from .logic import DangerzoneGui
  File "/usr/lib/python3/dist-packages/dangerzone/gui/logic.py", line 24, in <module>
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg.DesktopEntry'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_dangerzone.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.5.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/dangerzone/__init__.py", line 16, in <module>
    from .gui import gui_main as main
  File "/usr/lib/python3/dist-packages/dangerzone/gui/__init__.py", line 30, in <module>
    from .logic import DangerzoneGui
  File "/usr/lib/python3/dist-packages/dangerzone/gui/logic.py", line 24, in <module>
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg.DesktopEntry'

I tried uninstalling and installing everything, as well as restarting my computer, but it did not fix the problem. Unfortunately, I know nothing about coding, so I do not know how to fix this error. I AM able to run dangerzone as sudo dangerzone, but I do not know if that is a safe security practice. I never needed to run dangerzone as sudo before. If I type in sudo dangerzone for the first time, I get the following output.

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[DEBUG] Inferred system color scheme as OSColorMode.LIGHT
[DEBUG] Setting up Dangezone updater
[DEBUG] Consulting updater settings before checking for updates
[DEBUG] Checking platform type
[DEBUG] Running on Linux, disabling updates
[DEBUG] Will not check for updates, based on updater settings
[INFO] Installing Dangerzone container image...
Getting image source signatures
Copying blob 3728cd0a903d done  
Copying blob 9fe9a137fd00 done  
Copying blob efdce5fa126a done  
Copying blob 9778220be0ef done  
Copying blob b1532951420c done  
Copying blob 05dee8951dfc done  
Copying blob 87b72bc63a4d done  
Copying blob 429f271e92e2 done  
Copying config 7038ec45cd done  
Writing manifest to image destination
Storing signatures
Loaded image(s): dangerzone.rocks/dangerzone:latest
[INFO] Container image installed

And if I run it again, I get the following.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[DEBUG] Inferred system color scheme as OSColorMode.LIGHT
[DEBUG] Setting up Dangezone updater
[DEBUG] Consulting updater settings before checking for updates
[DEBUG] Checking platform type
[DEBUG] Running on Linux, disabling updates
[DEBUG] Will not check for updates, based on updater settings

As I said, the program works with sudo, but I am afraid of running any packages as sudo that do not need to be run as sudo. How do I fix this error? Do I need to set a XDG_RUNTIME_DIR for non-sudo user? I am new to Linux and coding, so I do not know. Would this fix the error, and if so, how would I do this? And what did I do to mess up XDG_RUNTIME_DIR in the first place, since the program was working before today (I do not think I have used it in some days, however)?

Thank you for your help. It is most appreciated. Please keep up the good fight, helping protect us from the bad guys.

**Comment by DeltaEpsilon19498** [comment] 2023-12-25 22:40
Thank you. I am using Linux Mint 21.2, codename Victoria, based on Ubuntu 22.04 LTS, which I believe is jammy.

If I try your suggestion, I get the following output.

sudo apt-get install python3-xdg          
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-xdg is already the newest version (0.27-2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

If I try sudo apt upgrade, I get the following output. 

sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  python3-update-manager update-manager-core
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

I do not know why the packages are being kept back. Is it that the linux mint devs have to look at them and approve of them before I am allowed to upgrade them?

Would it be better for me to try building dangerzone from source?

**Comment by DeltaEpsilon19498** [comment] 2023-12-25 23:32
I have followed the instructions on https://github.com/freedomofpress/dangerzone/blob/main/BUILD.md under the debian/ubuntu section. I created a .deb file, but the package still does not work. Here is the console output.

Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.5.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/dangerzone/__init__.py", line 16, in <module>
    from .gui import gui_main as main
  File "/usr/lib/python3/dist-packages/dangerzone/gui/__init__.py", line 30, in <module>
    from .logic import DangerzoneGui
  File "/usr/lib/python3/dist-packages/dangerzone/gui/logic.py", line 24, in <module>
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg.DesktopEntry'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_dangerzone.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/dangerzone", line 33, in <module>
    sys.exit(load_entry_point('dangerzone==0.5.1', 'console_scripts', 'dangerzone')())
  File "/usr/bin/dangerzone", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/dangerzone/__init__.py", line 16, in <module>
    from .gui import gui_main as main
  File "/usr/lib/python3/dist-packages/dangerzone/gui/__init__.py", line 30, in <module>
    from .logic import DangerzoneGui
  File "/usr/lib/python3/dist-packages/dangerzone/gui/logic.py", line 24, in <module>
    from xdg.DesktopEntry import DesktopEntry
ModuleNotFoundError: No module named 'xdg.DesktopEntry'

However, if I run from source tree, dangerzone DOES work. As long as I do each command one at a time, it runs. cd dangerzone
poetry shell
./dev_scripts/dangerzone

So that is good. I am new to linux, so I have to ask- is there any way I can do this from one command or one button press instead of three?

**Comment by apyrgio** [comment] 2023-12-29 16:07
Hi @DeltaEpsilon19498, thanks a lot for the bug report. Let's look a bit more into it:

As @deeplow already mentioned, this is the heart of the issue:

> File "/usr/lib/python3/dist-packages/dangerzone/gui/logic.py", line 24, in
> from xdg.DesktopEntry import DesktopEntry
> ModuleNotFoundError: No module named 'xdg.DesktopEntry'

Roughly, the Dangerzone code cannot import the `DesktopEntry` module from the `xdg` package, which is installed via `python3-xdg`.

You've given us some important hints:
1. `python3-xdg` is installed. I can see that its version (`0.27-2`) does contain the `xdg.DesktopEntry` module. This contradicts the error you are seeing.
2. When you run Dangerzone with `sudo`, it works. This is the expected behavior.
3. When you run Dangerzone from source, then it also works. That's interesting, but note that running Dangerzone from source uses a Python virtual environment, so the `xdg` module is not actually imported from the `python3-xdg` package.

My guess is that something in your **user** environment affects importing `xdg` from your system packages. Let's find out what that is. In my Linux Mint live CD, I get the following results when I run these following commands:

```console
python3 -c 'import xdg; print(xdg)'
sudo python3 -c 'import xdg; print(xdg)'
```

![Screenshot from 2023-12-29 17-56-07](https://github.com/freedomofpress/dangerzone/assets/2507626/7dc91e04-27bd-4c93-8f1c-9c918fd0da31)

Can you run those in your terminal as well?

**Comment by apyrgio** [comment] 2023-12-29 16:08
Also, I'll quickly address some of your other questions:


> I AM able to run dangerzone as sudo dangerzone, but I do not know if that is a safe security practice.

Nope, best not to do this. Best to run it from source, since you have done this already.

> I do not know why the packages are being kept back. Is it that the linux mint devs have to look at them and approve of them before I am allowed to upgrade them?

Probably these packages are kept back due to version requirements of other packages. I wouldn't worry much about it.

> I see that dangerzone is a python program. Is there any particular reason why dangerzone is not distributed through Pip/PyPi?

Because it requires Podman, which is a system package that cannot be installed via PyPI. Also, PyPI probably has some size limits, which the Dangerzone package would certainly surpass (currently it's ~620MiB).

> Also, in the line "Setting up Dangezone updater" is the misspelling of dangerzone intentional?

Welp, that's a typo :sweat_smile: , we'll fix it.

**Comment by DeltaEpsilon19498** [comment] 2024-01-02 03:13
Thank you for your help.

~$ python3 -c 'import xdg; print(xdg)'
<module 'xdg' from '/home/user/.local/lib/python3.10/site-packages/xdg/__init__.py'>

~$ sudo python3 -c 'import xdg; print(xdg)'
<module 'xdg' from '/usr/lib/python3/dist-packages/xdg/__init__.py'>

The first line is different.

**Comment by apyrgio** [comment] 2024-01-02 16:04
Thanks for the output of the commands. Indeed, the first command shows that you have a local version of `pyxdg` installed in `/home/user/.local/lib/python3.10/site-packages`. This masks the system one in `/usr/lib/python3/dist-packages`, and causes the breakage.

This may be the result of a `pip install` invocation, outside of a Python virtual environment. Do you recall installing a Python program this way? My suggestion would be to:

1. Find out what this program is (hint; you can list programs installed that way with `pip freeze`)
2. Install it in a virtual environment, or via some other method
3. Remove the `pyxdg` package, e.g., with `pip uninstall pyxdg`.

Hit us up if Dangerzone does not work after these changes. Other than that, I'm closing this issue since the error is not Dangerzone-related.

**Closed by apyrgio** 2024-01-02 16:04 UTC
