### ISSUE TITLE
QA and release 0.5.0

### ISSUE THREAD

**Issue by apyrgio** [freedomofpress/dangerzone#534] opened 2023-08-24 15:22 UTC
To ensure that new releases do not introduce regressions, and support existing and newer platforms, we have to run some QA tests. Copied from [RELEASE.md](https://github.com/freedomofpress/dangerzone/blob/main/RELEASE.md):

- [x] In `.circleci/config.yml`, add new platforms and remove obsolete platforms
- [x] Bump the Python dependencies using `poetry lock`
- [x] Make sure that the tip of the `main` branch passes the CI tests.
- [x] Make sure that the Apple account has a valid application password and has
      agreed to the latest Apple terms (see [macOS release](#macos-release)
      section).
- [x] Create a test build in Windows and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Build and run the Dangerzone .exe
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (Intel CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in macOS (M1/2 CPU) and make sure it works:
  - [x] Check if the suggested Python version is still supported.
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create and run an app bundle.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Ubuntu LTS platform (Ubuntu 22.04
  as of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create a .deb package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Fedora platform (Fedora 38 as of
  writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Build the container image and ensure the development environment uses
    the new image.
  - [x] Run the Dangerzone tests.
  - [x] Create an .rpm package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below).
- [x] Create a test build in the most recent Qubes Fedora template (Fedora 38 as
  of writing this) and make sure it works:
  - [x] Create a new development environment with Poetry.
  - [x] Run the Dangerzone tests.
  - [x] Create a Qubes .rpm package and install it system-wide.
  - [x] Test some QA scenarios (see [Scenarios](#Scenarios) below) and make sure
    they spawn disposable qubes.

_(see also the previous [QA for 0.4.2](https://github.com/freedomofpress/dangerzone/issues/458))_

**Comment by eloquence** [comment] 2023-10-12 21:08
I've used `qa.py` on an Ubuntu 23.04 host system to step through the automated and manual tests for the **Ubuntu 22.04** target platform.

I was not able to use `qa.py` on an Ubuntu 20.04 host system. The process errored out with "Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted". `fuse-overlayfs` is installed. I didn't dig further into this and unless you have some low-hanging fruit things to test it's probably not worth doing so since 20.04 is pretty long in the tooth.

## Automated tests

Automated test results all look good. I did get some deprecation warnings for which I've opened #595. There's also some warning output related to code coverage reporting and `shibokensupport`. The full output can be seen here: https://gist.github.com/eloquence/4a382d55ccb286e83de83043e88173bf

## Manual tests

> Dangerzone retains the settings of previous runs

The "Check for updates" setting does not persist for me. I've not tested if this problem occurs outside the QA environment. I've opened  #596 for this.

Other settings, e.g. "Open after converting", do persist.

> Updating Dangerzone handles external state correctly

I've not tested this yet. @deeplow I'd appreciate some pointers on this one - is this also testable with the `qa.py` setup, or should I manually build Dangerzone on the host system? If it can be done using `qa.py`, could you give me the steps I need to go through to ensure I'm testing both the container image and the Debian package in the expected manner?

All other test scenarios LGTM.

**Comment by deeplow** [comment] 2023-10-13 08:10
>>    Updating Dangerzone handles external state correctly
> 
> I've not tested this yet. @deeplow I'd appreciate some pointers on this one - is this also testable with the qa.py setup, or should I manually build Dangerzone on the host system? If it can be done using qa.py, could you give me the steps I need to go through to ensure I'm testing both the container image and the Debian package in the expected manner?

This is not trivial to test and it's particularly hard using our QA environment. Personally, I haven't been able to test that for the last two releases. But this is not ideal, so I've opened an issue to streamline this process #597

**Comment by deeplow** [comment] 2023-10-13 08:13
I also noticed that it was asking to test scenario 9 (Qubes-specific), so I marked it as "skippable" on Linux platforms #598

**Comment by deeplow** [comment] 2023-10-13 08:18
## Fedora 38 QA

I have just done the steps for QA on Fedora 38.

> > Dangerzone retains the settings of previous runs
> 
> The "Check for updates" setting does not persist for me. I've not tested if this problem occurs outside the QA environment. I've opened #596 for this.
> 
> Other settings, e.g. "Open after converting", do persist.

I can confirm that #596 also affects Fedora 38.

**Comment by eloquence** [comment] 2023-10-13 23:45
I was also able to test the upgrade scenario thanks to #605, no issues to report. :) Haven't gotten to Qubes yet. I should have some time for exploratory testing Monday afternoon. Please don't treat that as a blocker for the release, though.

Once we land Ubuntu 23.10 support I think we're otherwise looking in good shape - please correct me if I'm missing anything. The release mechanics themselves take a good amount of time, so I suggest we touch base Monday to settle on exact time/date. We may also want to confirm Lee's availability in case we hit any issues that require infra support.

**Comment by deeplow** [comment] 2023-10-19 21:15
All looks good [on the large tests](https://github.com/freedomofpress/dangerzone-test-set): 80 failures / 9748 docs.

**Closed by deeplow** 2023-10-19 21:15 UTC
Labels: development
