### ISSUE TITLE
Certain characters in the filename stop Dangerzone from working

### ISSUE THREAD

**Issue by micahflee** [freedomofpress/dangerzone#144] opened 2021-12-15 17:58 UTC
It looks like the characters `“` and `”` prevent Dangerzone from working, as in the filename: `“Wash Brains, Cleanse Hearts”_ Evidence from Chinese Government Documents about the Nature and Extent of Xinjiang’s Extrajudicial Internment Campaign _.pdf`

**Comment by zenmonkeykstop** [comment] 2022-03-22 01:38
Couldn't reproduce this under Linux (Ubuntu 20.04) on `main` - is there any specific OS under which it's failing?

**Comment by legoktm** [comment] 2022-03-22 17:05
The quoting on https://github.com/firstlookmedia/dangerzone/blob/8044f2276882e4d17570236138d024cecc80d61d/dangerzone/gui/main_window.py#L615 is suspicious, so maybe it's reproducible on Windows? (Also couldn't reproduce on Fedora 34/Qubes)

**Comment by noonespecific** [comment] 2022-03-22 17:35
On macOS 12.3, when running Dangerzone by double-clicking on the app, and loading the file a file called `Оригинал.png`, Dangerzone stalls and displays an empty progress bar indefinitely:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/56607624/159541029-f3b19588-dd8c-4257-8d40-f46e4e833f25.png">

When launching the dangerzone gui from the terminal (`/Applications/Dangerzone.app/Contents/MacOS/dangerzone`), or when using the dangerzone cli (`/Applications/Dangerzone.app/Contents/MacOS/dangerzone-cli Оригинал.png`), in both cases dangerzone converts the file successfully.

**Comment by micahflee** [comment] 2022-03-22 17:40
I've had to debug a few issues with dangerzone where there's a difference between running the GUI app from terminal vs. double-clicking the app to run it. The difference is the environment. In the terminal, the environment is inherited from the shell, but when you double-click it, there's different environment variables.

For example, I fixed a bug like this by making use `/usr/local/bin` is always in the `PATH` environment variable, which is is when you run from the terminal, but isn't when you double-click the app:

https://github.com/firstlookmedia/dangerzone/blob/main/dangerzone/gui/__init__.py#L45-L53

For some reason I can't reproduce this on my own Mac though--it just works for me when I double-click it.

**Comment by gmarmstrong** [comment] 2022-06-08 22:18
I can reproduce both issues (`“”` and `Оригинал`) on macOS 12.4 (Apple Silicon) from the v0.3.1 DMG on dangerzone.rocks. It only breaks when run from Finder. However, at least as of #164, I can no longer reproduce the issue. Unfortunately, I cannot build v0.3.1 from source since PySide2 doesn't support ARM, which makes it tricky to pinpoint which revision caused this.

> I've had to debug a few issues with dangerzone where there's a difference between running the GUI app from terminal vs. double-clicking the app to run it. The difference is the environment. In the terminal, the environment is inherited from the shell, but when you double-click it, there's different environment variables.
> 
> For example, I fixed a bug like this by making use `/usr/local/bin` is always in the `PATH` environment variable, which is is when you run from the terminal, but isn't when you double-click the app:
> 
> https://github.com/firstlookmedia/dangerzone/blob/main/dangerzone/gui/__init__.py#L45-L53

Worth noting that #164, since it upgrades to Qt 6, removes that "QT_MAC_WANTS_LAYER" environment variable since it will no longer be necessary. Also, does https://github.com/freedomofpress/dangerzone/blob/d8adb2e9cc1bee17ffe21a006cfc7878e4a13bc3/dangerzone/gui/__init__.py#L53 intentionally omit a ":$PATH" suffix?

> For some reason I can't reproduce this on my own Mac though--it just works for me when I double-click it.

I have a suspicion... @micahflee, can you reproduce the issue if you use the official https://github.com/freedomofpress/dangerzone/releases/download/v0.3.1/Dangerzone-0.3.1.dmg distribution? If so, then the build is non-deterministic. Even though PySide2 was pinned to version 5.15.2, the Qt binaries themselves are determined by whatever your Mac's Xcode SDK version was when you first created the DMG, which may have changed between December and March.

**Comment by yveszoundi** [comment] 2022-06-09 07:03
@gmarmstrong, as @micahflee already found out, there's indeed a difference between double-clicking on a "Mac OS app bundle" versus running the underlying executable from the terminal. 

I recently encountered that very same issue my "[Rust fork of Dangerzone](https://github.com/rimerosolutions/dangerzone-rust)"

- I mitigated it via a [wrapper shell script](https://github.com/rimerosolutions/dangerzone-rust/blob/main/ci_cd/darwin/macosx/Dangerzone) to "escape the sandbox" (invoke `docker`, `lima` or `podman` from the _PATH_): my approach could be a bit more robust though...
- Without mitigation, even it you were to temporarily hard-code the absolute path to `docker` in the program, it would still fail to find it... (double-click on app bundle scenario)

### References
There are probably better approaches than my solution, I'm more familiar with Linux than other operating systems.

#### Approaches to the problem
- This appears to be "the right way" of doing it: https://developer.apple.com/documentation/xcode/embedding-a-helper-tool-in-a-sandboxed-app
- Maybe this works too with assumptions of Docker for Desktop: https://stackoverflow.com/questions/27505022/open-another-mac-app
-  This is similar to what I did: https://github.com/mpv-player/mpv/issues/4658#issuecomment-318036293 

#### Other links
- https://stackoverflow.com/questions/12594380/how-to-launch-another-process-in-sandbox-on-mac
- https://apple.stackexchange.com/questions/26951/inserting-shell-script-into-app-bundle
- https://stackoverflow.com/questions/29282774/sandboxed-osx-app-with-command-line-helper-gives-unable-to-get-root-path
- https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/EntitlementKeyReference/Chapters/EnablingAppSandbox.html#//apple_ref/doc/uid/TP40011195-CH4-SW1

**Comment by deeplow** [comment] 2022-08-08 12:44
> The quoting on https://github.com/firstlookmedia/dangerzone/blob/8044f2276882e4d17570236138d024cecc80d61d/dangerzone/gui/main_window.py#L615 is suspicious, so maybe it's reproducible on Windows? (Also couldn't reproduce on Fedora 34/Qubes)

I was unable to reproduce this under windows (neither on v0.3.1 nor from main branch). So I guess this is a mac-specific issue as others report.

I was able to confirm all the findings above listed on an intel mac running macOS 12.0.

> Even though PySide2 was pinned to version 5.15.2, the Qt binaries themselves are determined by whatever your Mac's Xcode SDK version was when you first created the DMG, which may have changed between December and March.

I don't think this is it. I can reproduce it with an intel mac running on the main branch but it only happens when I build the app bundle and execute de Dangerzone.app. If I run it via `dev_scripts/dangerzone` or via `Contents/MacOS/dangerzone` it runs well.

**Comment by yveszoundi** [comment] 2022-08-09 05:32
It is indeed Mac OS specific issue:

- When you double-click or run directly the "Application Bundle" (`.app` folder), apparently application bundles run in some kind of sandbox by default (`PATH` restrictions for invoking "external" programs such as Docker, etc.).
- When the application scripts are run directly from a terminal or command prompt, my understanding is that it's literally a "sandbox escape".

**Comment by deeplow** [comment] 2022-08-09 15:15
I have a working fix for this. Turns out that it is [this print](https://github.com/freedomofpress/dangerzone/blob/v0.3.1/dangerzone/container.py#L30) that was causing us issues.

printing non-ascii characters in a macOS application opened directly from finder would sometimes lead to an error message in /var/log/system.log similar to this:
    
```
Failed to execute script 'dangerzone' due to unhandled exception: 'ascii' codec can't encode character '\u201c' in position 1:  ordinal not in range(128)
```


While I could not get exactly to the bottom of what it was happening in the first place (possibly related to the lack of encoding support on the stdout of a gui-only mac application), replacing prints with logging fixes this and should be preferred anyways, so I replaced them all and now the issue is fixed.

**Closed** 2022-08-18 11:22 UTC
Labels: bug, P:mac
